version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "15:05"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
